title: Sirens Hytale Mods
description: Docs for Sirens Hytale Mods!
theme: just-the-docs

url: https://mefroggy.github.io/sirenhytale

aux_links:
  Template Repository: https://github.com/mefroggy/sirenhytale
